# Generated by Django 5.0.6 on 2026-07-02 06:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypUvazku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, verbose_name='název')),
                ('hodiny_denne', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='hodin denně')),
                ('hodiny_tyydne', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='hodin týdně')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
            ],
            options={
                'verbose_name': 'typ úvazku',
                'verbose_name_plural': 'typy úvazků',
                'ordering': ['-hodiny_denne'],
            },
        ),
        migrations.CreateModel(
            name='Zeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, verbose_name='název')),
                ('kod', models.CharField(max_length=2, unique=True, verbose_name='kód ISO 3166-1')),
            ],
            options={
                'verbose_name': 'země',
                'verbose_name_plural': 'země',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'uživatel',
                'verbose_name_plural': 'uživatelé',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osobni_cislo', models.CharField(max_length=20, unique=True, verbose_name='osobní číslo')),
                ('datum_nastupu', models.DateField(verbose_name='datum nástupu')),
                ('datum_ukonceni', models.DateField(blank=True, null=True, verbose_name='datum ukončení')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='uživatel')),
            ],
            options={
                'verbose_name': 'zaměstnanec',
                'verbose_name_plural': 'zaměstnanci',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Odbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='název')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='kód')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
                ('vedouci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vedouci_odboru', to='accounts.employee', verbose_name='vedoucí')),
            ],
            options={
                'verbose_name': 'odbor',
                'verbose_name_plural': 'odbory',
                'ordering': ['sekce', 'nazev'],
            },
        ),
        migrations.CreateModel(
            name='Oddeleni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='název')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='kód')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
                ('odbor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oddeleni', to='accounts.odbor', verbose_name='odbor')),
                ('vedouci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vedouci_oddeleni', to='accounts.employee', verbose_name='vedoucí')),
            ],
            options={
                'verbose_name': 'oddělení',
                'verbose_name_plural': 'oddělení',
                'ordering': ['odbor', 'nazev'],
            },
        ),
        migrations.CreateModel(
            name='HistoriePrislusenosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_od', models.DateField(verbose_name='datum od')),
                ('datum_do', models.DateField(blank=True, null=True, verbose_name='datum do')),
                ('poznamka', models.TextField(blank=True, verbose_name='poznámka')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historie', to='accounts.employee', verbose_name='zaměstnanec')),
                ('zmenil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='změnil')),
                ('oddeleni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.oddeleni', verbose_name='oddělení')),
            ],
            options={
                'verbose_name': 'historie příslušnosti',
                'verbose_name_plural': 'historie příslušnosti',
                'ordering': ['-datum_od'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='oddeleni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zamestnanci', to='accounts.oddeleni', verbose_name='oddělení'),
        ),
        migrations.CreateModel(
            name='Sekce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='název')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='kód')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
                ('vedouci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vedouci_sekce', to='accounts.employee', verbose_name='vedoucí')),
            ],
            options={
                'verbose_name': 'sekce',
                'verbose_name_plural': 'sekce',
                'ordering': ['nazev'],
            },
        ),
        migrations.AddField(
            model_name='odbor',
            name='sekce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odbory', to='accounts.sekce', verbose_name='sekce'),
        ),
        migrations.AddField(
            model_name='employee',
            name='typ_uvazku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zamestnanci', to='accounts.typuvazku', verbose_name='typ úvazku'),
        ),
        migrations.CreateModel(
            name='StatniSvatek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='datum')),
                ('nazev', models.CharField(max_length=200, verbose_name='název')),
                ('firemni', models.BooleanField(default=False, help_text='Volno stanovené firmou, ne státem.', verbose_name='firemní volno')),
                ('zeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svatky', to='accounts.zeme', verbose_name='země')),
            ],
            options={
                'verbose_name': 'státní svátek',
                'verbose_name_plural': 'státní svátky',
                'ordering': ['datum'],
                'unique_together': {('zeme', 'datum')},
            },
        ),
    ]
