# Generated by Django 5.0.6 on 2026-07-07 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typuvazku',
            name='druh_pracovni_doby',
            field=models.CharField(choices=[('PRUZNA', 'Pružná'), ('PEVNA', 'Pevná')], default='PRUZNA', help_text='Pružná: jeden časový blok (jádrová doba). Pevná: jeden nebo více závazných časových bloků. Zatím jen evidence — bloky se nikde nevynucují, slouží jako podklad pro budoucí validaci.', max_length=10, verbose_name='druh pracovní doby'),
        ),
        migrations.CreateModel(
            name='CasovyBlokUvazku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blok_od', models.TimeField(verbose_name='od')),
                ('blok_do', models.TimeField(verbose_name='do')),
                ('typ_uvazku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casove_bloky', to='accounts.typuvazku', verbose_name='typ úvazku')),
            ],
            options={
                'verbose_name': 'časový blok pracovní doby',
                'verbose_name_plural': 'časové bloky pracovní doby',
                'ordering': ['blok_od'],
            },
        ),
    ]
