# Generated by Django 5.0.6 on 2026-07-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_typuvazku_druh_pracovni_doby_casovyblokuvazku'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='funkce',
            field=models.CharField(blank=True, choices=[('REDITEL_SEKCE', 'Ředitel sekce'), ('REDITEL_ODBORU', 'Ředitel odboru'), ('VEDOUCI_ODDELENI', 'Vedoucí oddělení'), ('SEKRETARIAT_ODBORU', 'Sekretariát odboru')], help_text="Řídící funkce v organizační hierarchii. Přiřazení automaticky nastaví odpovídající pole 'vedoucí' na sekci/odboru/oddělení a uvolní funkci předchozímu držiteli téže jednotky.", max_length=20, verbose_name='funkce'),
        ),
        migrations.AddField(
            model_name='odbor',
            name='zamestnanci_vidi_cely_odbor',
            field=models.BooleanField(default=True, help_text='Zapnuto (výchozí): řadoví zaměstnanci bez funkce vidí v přehledech přítomnosti/týmu všechny zaměstnance odboru napříč odděleními. Vypnuto: vidí jen zaměstnance vlastního oddělení.', verbose_name='zaměstnanci vidí celý odbor'),
        ),
    ]
