# Generated by Django 5.0.6 on 2026-07-09 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_zpetne_dosazeni_funkce_z_vedouciho'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rucne_nepritomen',
            field=models.BooleanField(default=False, help_text='Dočasné přepnutí mimo evidenci dovolené/nemoci (např. služební cesta) — pokud je zapnuto, schvalování žádostí podřízených přebírá nastavený zástupce.', verbose_name='ručně označen jako nepřítomný'),
        ),
        migrations.AddField(
            model_name='employee',
            name='zastupce',
            field=models.ForeignKey(blank=True, help_text='Zástupce má trvale stejná práva na správu zaměstnanců jako tento zaměstnanec a přebírá schvalování žádostí, pokud je tento zaměstnanec označen jako nepřítomný. Musí být ze stejné organizační jednotky, na kterou je vázaná funkce.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zastupovani_za', to='accounts.employee', verbose_name='zástupce'),
        ),
    ]
