# Generated by Django 5.0.6 on 2026-09-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employee_funkce_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typuvazku',
            name='druh_pracovni_doby',
            field=models.CharField(choices=[('PRUZNA', 'Pružná'), ('PEVNA', 'Pevná')], default='PRUZNA', help_text='Pružná: jeden časový blok (jádrová doba). Pevná: jeden nebo více závazných časových bloků. Jádrová doba pružného úvazku se využívá při výpočtu odpracované doby u pohybů s příznakem „započítává se u pružné pracovní doby“. Jinak jsou bloky zatím jen evidence — příchody a odchody se vůči nim nekontrolují a bloky pevné pracovní doby nevyužívá žádný výpočet.', max_length=10, verbose_name='druh pracovní doby'),
        ),
    ]
