# Generated by Django 5.0.6 on 2026-09-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_typuvazku_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='casovyblokuvazku',
            name='ctvrtek',
            field=models.BooleanField(default=False, verbose_name='čtvrtek'),
        ),
        migrations.AddField(
            model_name='casovyblokuvazku',
            name='nedele',
            field=models.BooleanField(default=False, verbose_name='neděle'),
        ),
        migrations.AddField(
            model_name='casovyblokuvazku',
            name='patek',
            field=models.BooleanField(default=False, verbose_name='pátek'),
        ),
        migrations.AddField(
            model_name='casovyblokuvazku',
            name='pondeli',
            field=models.BooleanField(default=False, verbose_name='pondělí'),
        ),
        migrations.AddField(
            model_name='casovyblokuvazku',
            name='sobota',
            field=models.BooleanField(default=False, verbose_name='sobota'),
        ),
        migrations.AddField(
            model_name='casovyblokuvazku',
            name='streda',
            field=models.BooleanField(default=False, verbose_name='středa'),
        ),
        migrations.AddField(
            model_name='casovyblokuvazku',
            name='utery',
            field=models.BooleanField(default=False, verbose_name='úterý'),
        ),
    ]
