# Generated by Django 5.0.6 on 2026-09-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_casovyblokuvazku_dny_v_tydnu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typuvazku',
            name='druh_pracovni_doby',
            field=models.CharField(choices=[('PRUZNA', 'Pružná'), ('PEVNA', 'Pevná')], default='PRUZNA', help_text='Pružná: jeden časový blok (jádrová doba). Pevná: jeden nebo více závazných časových bloků, každý se zaškrtnutými dny v týdnu, kdy platí. Jádrová doba pružného úvazku se využívá při výpočtu odpracované doby u pohybů s příznakem „započítává se u pružné pracovní doby“. U pevné pracovní doby se odpracovaná doba ořízne na bloky platné pro daný den — den bez zaškrtnutého bloku dá 0 odpracovaných minut. Příchody a odchody se vůči blokům nekontrolují, jen se podle nich počítá odpracovaná doba.', max_length=10, verbose_name='druh pracovní doby'),
        ),
    ]
