# Generated by Django 5.0.6 on 2026-07-02 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypDovolene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, verbose_name='název')),
                ('zkratka', models.CharField(max_length=10, verbose_name='zkratka')),
                ('odecita_ze_zustatku', models.BooleanField(default=True, help_text='Např. nemoc se neodečítá z dovolené.', verbose_name='odečítá ze zůstatku dovolené')),
                ('barva', models.CharField(default='#4A90E2', help_text='Barva pro zobrazení v kalendáři.', max_length=7, verbose_name='barva (hex)')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
            ],
            options={
                'verbose_name': 'typ dovolené',
                'verbose_name_plural': 'typy dovolené',
            },
        ),
        migrations.CreateModel(
            name='ZadostODovolenou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_od', models.DateField(verbose_name='datum od')),
                ('datum_do', models.DateField(verbose_name='datum do')),
                ('pocet_hodin', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='počet hodin')),
                ('stav', models.CharField(choices=[('ceka', 'Čeká na schválení'), ('schvaleno', 'Schváleno'), ('zamitnuto', 'Zamítnuto'), ('stornovano', 'Stornováno')], default='ceka', max_length=12, verbose_name='stav')),
                ('schvaleno_kdy', models.DateTimeField(blank=True, null=True, verbose_name='schváleno kdy')),
                ('poznamka_zamestnance', models.TextField(blank=True, verbose_name='poznámka zaměstnance')),
                ('poznamka_schvalovatele', models.TextField(blank=True, verbose_name='poznámka schvalovatele')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('upraveno', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zadosti_o_dovolenou', to='accounts.employee', verbose_name='zaměstnanec')),
                ('schvaleno_kym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schvalil_zadosti', to='accounts.employee', verbose_name='schválil')),
                ('schvalovatele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ke_schvaleni', to='accounts.employee', verbose_name='schvaluje')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaves.typdovolene', verbose_name='typ')),
            ],
            options={
                'verbose_name': 'žádost o dovolenou',
                'verbose_name_plural': 'žádosti o dovolenou',
                'ordering': ['-vytvoreno'],
            },
        ),
        migrations.CreateModel(
            name='ZustatekDovolene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.PositiveSmallIntegerField(verbose_name='rok')),
                ('narok_hodin', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='nárok (hod)')),
                ('cerpano_hodin', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='čerpáno (hod)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zustatky_dovolene', to='accounts.employee', verbose_name='zaměstnanec')),
            ],
            options={
                'verbose_name': 'zůstatek dovolené',
                'verbose_name_plural': 'zůstatky dovolené',
                'ordering': ['-rok'],
                'unique_together': {('employee', 'rok')},
            },
        ),
    ]
