# Generated by Django 5.0.6 on 2026-07-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NarokIndispozicnihoVolna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodin', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='hodin')),
                ('platne_od', models.DateField(verbose_name='platné od')),
            ],
            options={
                'verbose_name': 'nárok na indispoziční volno',
                'verbose_name_plural': 'nárok na indispoziční volno',
                'ordering': ['-platne_od'],
            },
        ),
        migrations.AddField(
            model_name='typdovolene',
            name='je_indispozicni_volno',
            field=models.BooleanField(default=False, help_text='Nárok se pro tento typ automaticky dosazuje z globálního nastavení (NarokIndispozicnihoVolna), ne ručně na zaměstnance.', verbose_name='je indispoziční volno'),
        ),
        migrations.AddField(
            model_name='zustatekdovolene',
            name='typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zustatky', to='leaves.typdovolene', verbose_name='typ'),
        ),
    ]
