# Generated by Django 5.0.6 on 2026-07-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('leaves', '0003_seed_and_backfill_typ'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zustatekdovolene',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='zustatekdovolene',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zustatky', to='leaves.typdovolene', verbose_name='typ'),
        ),
        migrations.AlterUniqueTogether(
            name='zustatekdovolene',
            unique_together={('employee', 'rok', 'typ')},
        ),
    ]
