# Generated by Django 5.0.6 on 2026-07-03 06:32

from django.db import migrations, models


def backfill_kategorie(apps, schema_editor):
    """
    Nastaví kategorie_pro_prehled na existujících typech dovolené, aby
    denní přehled přítomnosti (issue #3) hned po nasazení správně rozeznal
    indispoziční volno a dovolenou. Nové typy (služební volno, OČR) je
    nutné po nasazení ručně založit v administraci.
    """
    TypDovolene = apps.get_model("leaves", "TypDovolene")

    TypDovolene.objects.filter(je_indispozicni_volno=True).update(
        kategorie_pro_prehled="INDISPOZICNI_VOLNO"
    )
    TypDovolene.objects.filter(
        je_indispozicni_volno=False, odecita_ze_zustatku=True
    ).update(kategorie_pro_prehled="DOVOLENA")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_enforce_zustatek_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='typdovolene',
            name='kategorie_pro_prehled',
            field=models.CharField(choices=[('DOVOLENA', 'Dovolená'), ('NEMOC', 'Nemoc'), ('INDISPOZICNI_VOLNO', 'Indispoziční volno'), ('SLUZEBNI_VOLNO', 'Služební volno'), ('OCR', 'Ošetřování člena rodiny'), ('JINA', 'Jiná absence')], default='JINA', help_text='Určuje, pod jakou kategorií se schválené žádosti tohoto typu zobrazí v denním přehledu přítomnosti a vyhledání zaměstnance.', max_length=20, verbose_name='kategorie pro přehled přítomnosti'),
        ),
        migrations.RunPython(backfill_kategorie, noop_reverse),
    ]
