# Generated by Django 5.0.6 on 2026-07-04 08:26

from django.db import migrations, models


def oznac_typ_dovolena(apps, schema_editor):
    """Nastaví je_dovolena=True na seedovaném typu s kategorií DOVOLENA."""
    TypStavu = apps.get_model("leaves", "TypStavu")
    TypStavu.objects.filter(kategorie_pro_prehled="DOVOLENA").update(je_dovolena=True)


def odznac_typ_dovolena(apps, schema_editor):
    TypStavu = apps.get_model("leaves", "TypStavu")
    TypStavu.objects.filter(kategorie_pro_prehled="DOVOLENA").update(je_dovolena=False)


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_rename_typ_stavu'),
    ]

    operations = [
        migrations.CreateModel(
            name='NarokDovolene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodin', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='hodin')),
                ('platne_od', models.DateField(verbose_name='platné od')),
            ],
            options={
                'verbose_name': 'nárok na dovolenou',
                'verbose_name_plural': 'nárok na dovolenou',
                'ordering': ['-platne_od'],
            },
        ),
        migrations.AddField(
            model_name='typstavu',
            name='je_dovolena',
            field=models.BooleanField(default=False, help_text='Nárok se pro tento typ každý rok automaticky aktualizuje (zbytek z minulého roku + roční nárok z NarokDovolene) příkazem obnov_rocni_naroky.', verbose_name='je dovolená'),
        ),
        migrations.RunPython(oznac_typ_dovolena, odznac_typ_dovolena),
    ]
