# Generated by Django 5.0.6 on 2026-10-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0009_hodinova_zadost'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadostostav',
            name='samoschvaleno',
            field=models.BooleanField(default=False, help_text='Schvalovatel schválil vlastní žádost ve výjimečném případě (důvod je v poznámce schvalovatele).', verbose_name='schváleno vlastní osobou'),
        ),
    ]
