# Generated by Django 5.0.6 on 2026-10-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0010_zadost_samoschvaleno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typstavu',
            name='odecita_ze_zustatku',
            field=models.BooleanField(default=True, help_text='Schválená žádost se odečte z ročního zůstatku tohoto typu (např. dovolená, indispoziční volno). Např. nemoc se neodečítá.', verbose_name='odečítá ze zůstatku'),
        ),
    ]
