# Generated by Django 5.0.6 on 2026-07-02 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zacatek', models.DateTimeField(verbose_name='začátek')),
                ('konec', models.DateTimeField(blank=True, null=True, verbose_name='konec')),
                ('zdroj', models.CharField(choices=[('prichod', 'Příchod přes web'), ('rucni', 'Ruční zápis / oprava')], default='prichod', max_length=10, verbose_name='zdroj záznamu')),
                ('poznamka', models.TextField(blank=True, verbose_name='poznámka')),
                ('opraveno', models.BooleanField(default=False, help_text='Označeno, pokud byl záznam doplněn/opraven zpětně.', verbose_name='ručně opraveno')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('upraveno', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.employee', verbose_name='zaměstnanec')),
            ],
            options={
                'verbose_name': 'pracovní blok',
                'verbose_name_plural': 'pracovní bloky',
                'ordering': ['-zacatek'],
            },
        ),
        migrations.CreateModel(
            name='WorkdaySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='datum')),
                ('hrube_minuty', models.PositiveIntegerField(default=0, verbose_name='hrubé minuty')),
                ('prestavka_minuty', models.PositiveIntegerField(default=0, help_text='30 min odečteno při práci přes 6 hodin.', verbose_name='přestávka (min)')),
                ('odpracovane_minuty', models.PositiveIntegerField(default=0, verbose_name='odpracované minuty')),
                ('prescos_minuty', models.IntegerField(default=0, verbose_name='přesčas (min)')),
                ('je_svatek', models.BooleanField(default=False, verbose_name='státní svátek')),
                ('je_vikend', models.BooleanField(default=False, verbose_name='víkend')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denni_souhrny', to='accounts.employee', verbose_name='zaměstnanec')),
            ],
            options={
                'verbose_name': 'denní souhrn',
                'verbose_name_plural': 'denní souhrny',
                'ordering': ['-datum'],
                'unique_together': {('employee', 'datum')},
            },
        ),
    ]
