# Generated by Django 5.0.6 on 2026-07-07 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypPohybu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, verbose_name='název')),
                ('zkratka', models.CharField(max_length=10, verbose_name='zkratka')),
                ('zapocitava_se_do_pracovni_doby', models.BooleanField(default=False, help_text='Vypnuto (výchozí): doba pohybu se odečte z odpracované doby (např. oběd, soukromá záležitost). Zapnuto: doba pohybu se neodečítá, práce běží dál (např. placená přestávka).', verbose_name='započítává se do pracovní doby')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
            ],
            options={
                'verbose_name': 'typ pohybu',
                'verbose_name_plural': 'typy pohybu',
            },
        ),
        migrations.AddField(
            model_name='workdaysummary',
            name='pohyby_minuty',
            field=models.PositiveIntegerField(default=0, help_text='Součet dokončených pohybů, jejichž typ se nezapočítává do pracovní doby.', verbose_name='odečtené pohyby (min)'),
        ),
        migrations.CreateModel(
            name='Pohyb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zacatek', models.DateTimeField(verbose_name='začátek')),
                ('konec', models.DateTimeField(blank=True, null=True, verbose_name='konec')),
                ('poznamka', models.TextField(blank=True, verbose_name='poznámka')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('upraveno', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pohyby', to='timetracking.worksession', verbose_name='pracovní blok')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetracking.typpohybu', verbose_name='typ pohybu')),
            ],
            options={
                'verbose_name': 'pohyb',
                'verbose_name_plural': 'pohyby',
                'ordering': ['-zacatek'],
            },
        ),
    ]
