# Generated by Django 5.0.6 on 2026-07-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0002_typpohybu_workdaysummary_pohyby_minuty_pohyb'),
    ]

    operations = [
        migrations.AddField(
            model_name='typpohybu',
            name='zapocitava_se_u_pruzne_pracovni_doby',
            field=models.BooleanField(default=False, help_text='Zapnuto: u zaměstnanců s pružnou pracovní dobou se doba pohybu do odpracované doby započítává jen v pevné (jádrové) části pracovní doby (např. 9–14 hod.); mimo ni se nezapočítává. Zatím jen evidence — logika se nikde nevynucuje.', verbose_name='započítává se u pružné pracovní doby'),
        ),
        migrations.AddField(
            model_name='typpohybu',
            name='zobrazuje_se_na_pracovisti',
            field=models.BooleanField(default=False, help_text='Zapnuto: zaměstnanec je po dobu pohybu v denním přehledu přítomnosti nadále veden jako na pracovišti (např. přestávka v areálu). Vypnuto (výchozí): pohyb znamená nepřítomnost na pracovišti (např. lékař, soukromá záležitost).', verbose_name='zobrazuje se na pracovišti'),
        ),
    ]
