# Generated by Django 5.0.6 on 2026-07-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0003_typpohybu_zapocitava_se_u_pruzne_pracovni_doby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdaysummary',
            name='pohyby_minuty',
            field=models.PositiveIntegerField(default=0, help_text='Součet dokončených pohybů, jejichž typ se nezapočítává do pracovní doby, a u pružné pracovní doby i té části pohybů „započítávaných u pružné pracovní doby“, která leží mimo jádrovou (pevnou) dobu úvazku.', verbose_name='odečtené pohyby (min)'),
        ),
    ]
