# Generated by Django 5.0.6 on 2026-09-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0004_alter_workdaysummary_pohyby_minuty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typpohybu',
            name='zapocitava_se_u_pruzne_pracovni_doby',
            field=models.BooleanField(default=False, help_text='Zapnuto: u zaměstnanců s pružnou pracovní dobou se doba pohybu do odpracované doby započítává jen v pevné (jádrové) části pracovní doby (např. 9–14 hod.); část mimo ni se odečte jako u běžného pohybu. Má smysl jen spolu se zapnutým „započítává se do pracovní doby“.', verbose_name='započítává se u pružné pracovní doby'),
        ),
        migrations.AlterField(
            model_name='typpohybu',
            name='zobrazuje_se_na_pracovisti',
            field=models.BooleanField(default=False, help_text='Zatím jen evidence — denní přehled přítomnosti tento příznak nečte, takže na nic nemá vliv. Zamýšlený význam: zapnuto = zaměstnanec je po dobu pohybu nadále veden jako na pracovišti (např. přestávka v areálu), vypnuto (výchozí) = pohyb znamená nepřítomnost na pracovišti (např. lékař, soukromá záležitost).', verbose_name='zobrazuje se na pracovišti'),
        ),
    ]
